//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string SubmissionId { get; set; }
        public string data { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Submission Submission { get; set; }
    }
}
